# Generated by Django 3.1 on 2021-01-12 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('Sr_No', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(blank=True)),
                ('Time', models.TimeField(blank=True)),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Memo', models.TextField(blank=True, null=True)),
                ('Link', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('Sr_No', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(blank=True)),
                ('Time', models.TimeField(blank=True)),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Memo', models.TextField(blank=True, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
                ('Batch', models.CharField(default='0000-00', max_length=7)),
                ('Participants', models.ManyToManyField(blank=True, default=None, related_name='Participants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.CharField(choices=[("I'm In", "I'm In"), ("I'm Out", "I'm Out")], default="I'm In", max_length=10)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.reunion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('Sr_No', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(blank=True, max_length=300, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Static/Doubts')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('answers', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doubt_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='connect.doubt')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connect.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Memo', models.TextField(blank=True, null=True)),
                ('visible', models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], default='Hide', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
