# Generated by Django 3.1 on 2021-01-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='static/doubts'),
        ),
    ]
