# Generated by Django 3.1 on 2020-09-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunion',
            name='Batch',
        ),
    ]
