# Generated by Django 3.1 on 2021-01-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20210114_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='doubts'),
        ),
    ]
