# Generated by Django 3.1 on 2020-09-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_remove_reunion_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunion',
            name='Date',
        ),
    ]
