# Generated by Django 3.1 on 2020-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_auto_20200925_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='Batch',
            field=models.CharField(default='0000-00', max_length=7),
        ),
    ]
