# Generated by Django 3.1 on 2020-09-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_reunion_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='participants',
            field=models.CharField(choices=[("I'm In", "I'm In"), ("I'm Out", "I'm Out")], default="I'm In", max_length=10),
        ),
    ]
