# Generated by Django 3.1.1 on 2020-09-30 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connect', '0008_auto_20200926_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('Sr_No', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(blank=True)),
                ('Time', models.TimeField(blank=True)),
                ('Title', models.CharField(blank=True, max_length=20, null=True)),
                ('Memo', models.TextField(blank=True, null=True)),
                ('Link', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Memo', models.TextField(blank=True, null=True)),
                ('visible', models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], default='Hide', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
