# Generated by Django 3.1.1 on 2020-10-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_auto_20200930_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
