# Generated by Django 3.1 on 2020-09-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_auto_20200930_1652'),
        ('connect', '0009_webinar'),
    ]

    operations = [
    ]
