# Generated by Django 3.1 on 2020-10-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_auto_20201004_1404'),
        ('connect', '0009_webinar'),
    ]

    operations = [
    ]
