# Generated by Django 3.1 on 2020-10-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_merge_20200930_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
