# Generated by Django 3.1 on 2020-10-05 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connect', '0011_merge_20201004_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='Link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('Sr_No', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(blank=True, max_length=300, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Static/Doubts')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('answers', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doubt_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.doubt')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connect.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
