# Generated by Django 3.1 on 2020-10-06 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0012_auto_20201005_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='doubt_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='connect.doubt'),
        ),
    ]
