# Generated by Django 3.1 on 2020-10-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201003_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
