# Generated by Django 3.1 on 2020-10-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201003_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='msg',
            new_name='comments',
        ),
    ]
