# Generated by Django 3.1 on 2020-09-23 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Sr_No', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Sr_No', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(blank=True, choices=[('Alumni', 'Alumni'), ('Student', 'Student')], default='NA', max_length=100, null=True)),
                ('Graduation_Starting_Year', models.IntegerField(blank=True, default=0, null=True)),
                ('Graduation_Ending_Year', models.IntegerField(blank=True, default=0, null=True)),
                ('Branch', models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Electronics & Telecommunication', 'Electronics & Telecommunication'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Others', 'Others')], default='NA', max_length=100, null=True)),
                ('PRN_No', models.IntegerField(blank=True, default=0, null=True)),
                ('Final_CGPA', models.IntegerField(blank=True, default=0, null=True)),
                ('Mobile_No', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('Profile_Photo', models.ImageField(blank=True, default='media/Static/home/dypiemr.jpg', null=True, upload_to='Static/home')),
                ('Bio', models.CharField(blank=True, default='NA', max_length=1000, null=True)),
                ('Job', models.CharField(blank=True, default='NA', max_length=500, null=True)),
                ('Project', models.CharField(blank=True, default='NA', max_length=500, null=True)),
                ('Technical_Skills', models.CharField(blank=True, default='NA', max_length=500, null=True)),
                ('Hobbies', models.CharField(blank=True, default='NA', max_length=500, null=True)),
                ('Time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
