# Generated by Django 3.1 on 2020-09-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Graduation_Ending_Year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Graduation_Starting_Year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
