# Generated by Django 3.1 on 2021-01-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Profile_Photo',
            field=models.ImageField(blank=True, default='static/home/default.png', null=True, upload_to='static/home'),
        ),
    ]
