# Generated by Django 3.1 on 2020-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200929_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Profile_Photo',
            field=models.ImageField(blank=True, default='home/dypiemr.jpg', null=True, upload_to='Static/home'),
        ),
    ]
