# Generated by Django 3.1 on 2020-09-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200929_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Profile_Photo',
            field=models.ImageField(blank=True, default='Static/home/DigitalQue.PNG', null=True, upload_to='Static/home'),
        ),
    ]
