# Generated by Django 3.1 on 2021-01-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210114_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Time',
            new_name='time',
        ),
    ]
