# Generated by Django 3.1 on 2020-09-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200929_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Profile_Photo',
            field=models.ImageField(blank=True, default='Static/home/default.png', null=True, upload_to='Static/home'),
        ),
    ]
