# Generated by Django 3.1.1 on 2020-10-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200929_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Graduation_Ending_Year',
            field=models.IntegerField(blank=True, choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Graduation_Starting_Year',
            field=models.IntegerField(blank=True, choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], null=True),
        ),
    ]
