# Generated by Django 3.1 on 2020-10-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201004_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Profile_Photo',
            field=models.ImageField(blank=True, default='Static/Home/default.png', null=True, upload_to='Static/Home'),
        ),
    ]
